// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCH6mLuNYzM2EfT76YXkeICrdxjTh2FN04',
    appId: '1:229948327833:web:31e8a88e09984423c3f508',
    messagingSenderId: '229948327833',
    projectId: 'limix-app',
    authDomain: 'limix-app.firebaseapp.com',
    storageBucket: 'limix-app.firebasestorage.app',
    measurementId: 'G-HSQR4LJKYR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD3ZjPQLi8T84LbLHf9QYN4H0R0iOB16k',
    appId: '1:229948327833:android:f289aa23a89e0d15c3f508',
    messagingSenderId: '229948327833',
    projectId: 'limix-app',
    storageBucket: 'limix-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTPKUlbxCPRBayuqlR2oE9-ytgWPUSuic',
    appId: '1:229948327833:ios:928ed90c04800aa4c3f508',
    messagingSenderId: '229948327833',
    projectId: 'limix-app',
    storageBucket: 'limix-app.firebasestorage.app',
    iosBundleId: 'com.example.limixTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTPKUlbxCPRBayuqlR2oE9-ytgWPUSuic',
    appId: '1:229948327833:ios:928ed90c04800aa4c3f508',
    messagingSenderId: '229948327833',
    projectId: 'limix-app',
    storageBucket: 'limix-app.firebasestorage.app',
    iosBundleId: 'com.example.limixTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCH6mLuNYzM2EfT76YXkeICrdxjTh2FN04',
    appId: '1:229948327833:web:ba5a7d807d90c936c3f508',
    messagingSenderId: '229948327833',
    projectId: 'limix-app',
    authDomain: 'limix-app.firebaseapp.com',
    storageBucket: 'limix-app.firebasestorage.app',
    measurementId: 'G-NWRXWTHQMC',
  );
}
